### ISSUE TITLE
Pending issues

### ISSUE THREAD

**Issue by RMattHutchison** [Brainhack-Proceedings-2015/Margulies-AMX-Surfdist#4]
Margulies and colleagues present a very interesting (and likely very useful) tool for examining geodesic distance on the cortical surface. I have seen some of the results from this approach from this lab that really highlights the power of the technique. The report is well written and clear. I have only several minor suggestions to improve it.
1.  A methods/pipeline figure would be beneficial. This could be purely text based, though would be better augmented by images. This would visualize the steps, and/or calculation of distance.
2.  Add a colorbar to the top row of Figure 1. 
3.  Consider a different color scheme for the bottom row (zones) of Figure 1 to better delineate from the top row (exact distance).
4.  In brackets or a footnote define Voronoi diagram.

R. Matthew Hutchison

**Comment by margulies** [comment]
Many thanks for the helpful suggestions. In response, we have address all the concerns as described below:
1. We have added a visual pipeline in part B of Figure 1. 
2. We have now added a colorbar depicting the scaling of distance. 
3. We have modified the color scheme for the labels.
4. We now describe the Voronoi diagram in the text as follows:
   
   "The zones analysis constructs a Voronoi diagram, which establishes partitions based on the greater proximity to a set of label nodes."

Please let us know if any of the points you raised could be further addressed -- happy to do so...

Best regards, 
Daniel, on behalf of the authors

**Comment by margulies** [comment]
We have now further modified the figure to help improve legibility -- any suggestions would be very much appreciated.

**Comment by RMattHutchison** [comment]
Everything looks great and excited to apply Surfeits to some real data!

**Comment by margulies** [comment]
Thanks!
